name: pull requests and merges

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

permissions:
  contents: none

jobs:
  ci:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca

      - name: Install dependencies
        run: uv sync --dev

      - name: Lint code
        run: uv run make ruff-lint

      - name: Run tests
        run: uv run make test
